### ISSUE TITLE
Extension build using docker is failing to start

### ISSUE THREAD

**Issue by artplan1** [vscode-icons/vscode-icons#1431]
- [x] I'm sure this issue is not a _duplicate_.

When I'm trying to run extension build using docker it fails.

<details>
<summary>Docker log</summary>

```
docker build -t dev docker/development
....
Successfully built 6dd12c1518cd
Successfully tagged dev:latest

docker run --rm -it -v $(PWD):/app dev
npm info it worked if it ends with ok
npm info using npm@5.4.2
npm info using node@v8.7.0
npm info lifecycle vscode-icons@7.19.0~preinstall: vscode-icons@7.19.0
npm WARN lifecycle vscode-icons@7.19.0~preinstall: cannot run in wd %s %s (wd=%s) vscode-icons@7.19.0 git submodule update --init --recursive /app
npm ERR! code ENOLOCAL
npm ERR! Could not install from "submodules/examples-generator" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-27T00_15_41_952Z-debug.log
module.js:473
      throw err;
      ^

Error: Cannot find module '/app/node_modules/vscode/bin/install'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm info it worked if it ends with ok
npm info using npm@5.4.2
npm info using node@v8.7.0
npm info lifecycle vscode-icons@7.19.0~prebuild: vscode-icons@7.19.0

> vscode-icons@7.19.0 prebuild /app
> npm run lint && npm run test

npm info it worked if it ends with ok
npm info using npm@5.4.2
npm info using node@v8.7.0
npm info lifecycle vscode-icons@7.19.0~prelint: vscode-icons@7.19.0
npm info lifecycle vscode-icons@7.19.0~lint: vscode-icons@7.19.0

> vscode-icons@7.19.0 lint /app
> tslint -p .

sh: tslint: not found
npm info lifecycle vscode-icons@7.19.0~lint: Failed to exec lint script
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vscode-icons@7.19.0 lint: `tslint -p .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the vscode-icons@7.19.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-27T00_15_42_558Z-debug.log
npm info lifecycle vscode-icons@7.19.0~prebuild: Failed to exec prebuild script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-icons@7.19.0 prebuild: `npm run lint && npm run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-icons@7.19.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-27T00_15_42_572Z-debug.log
```
</details

So we can see in log that it's failing because of this:
```
npm WARN lifecycle vscode-icons@7.19.0~preinstall: cannot run in wd %s %s (wd=%s) vscode-icons@7.19.0 git submodule update --init --recursive /app
```

Possible solutions:

When I change `install.sh` to run `git submodule update --init --recursive` before `npm i` it installs packages correctly.

**Comment by robertohuertasm** [comment]
Hi @artplan1, thanks for reporting the issue. I've already made a PR with a fix.

**Comment by artplan1** [comment]
@robertohuertasm tried your fix, it works. Thank you for quick response and fix.

**Comment by JimiC** [comment]
@artplan1 Does `docker run --rm -it -v $(PWD):/app dev` runs to completion with @robertohuertasm fix?
I mean does `npm install` finishes successfully? I have seen it fail trying to build `nodegit`.

**Comment by artplan1** [comment]
@JimiC 
yeah, it fails for me too:

<details>
<summary>Log</summary>

```
nodegit@0.18.3 install /app/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /app/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/app/node_modules/nodegit/vendor/openssl/openssl
/app/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/app/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/app/node_modules/nodegit/vendor/libssh2':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/app/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/app/node_modules/nodegit/vendor/openssl/openssl' }
/app/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/app/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/app/node_modules/nodegit/vendor/libssh2':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /app/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/app/node_modules/nodegit/vendor/openssl/openssl
/app/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/app/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/app/node_modules/nodegit/vendor/libssh2':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/app/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/app/node_modules/nodegit/vendor/openssl/openssl' }
npm info lifecycle nodegit@0.18.3~install: Failed to exec install script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.18.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.18.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-02T09_27_07_825Z-debug.log
Detected VS Code engine version: ^1.8.1
Found minimal version that qualifies engine range: 1.8.1
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/ee428b0eead68bf0fb99ab5fdc4439be227b6281/src/vs/vscode.d.ts
vscode.d.ts successfully installed!
```
</details>

but build finishes with success in the end

**Comment by JimiC** [comment]
Great! Cause I have a fix for that. I'm experimenting with `docker` these days and what best way to learn by using our own project. 😄

**Comment by artplan1** [comment]
@JimiC so to fix you added some additional ssl dev libs to image or linked it correctly to paths? I read sooo many complaints about `nodegit` installation 😀

**Comment by JimiC** [comment]
No. The problem is not with `libgit`. It's just that the `alpine` image doesn't have the tools needed to build `nodegit`. A PR will come soon.

**Comment by JimiC** [comment]
Just an update.
Although I have the docker image build `nodegit` there are some issues.
Currently, we can build `nodegit` against `node 8.7.0` because in this case `nodegit` is built from source as `nodegit@0.18.3`, the version that we use, is not built against `node 8` and thus has no binaries on S3.
If we try to use `node 7.9.0` (which we should as `vscode` is still in that version), we fetcht the S3 binaries but the build fails due to issues with `alpine-3.4` (which the `node:7.9.0-alpine` image uses) and the C compiler.

So, I'm exploring other ways to make the image suit our needs, and it will take some time to find the honeypot.

@robertohuertasm I'm also looking into the option to make our own `docker` images and upload it to `Docker Hub`. Thoughts?

**Comment by robertohuertasm** [comment]
If you want to try it I would do it only for the development Dockerfile. I have already created the organization. I would need your docker hub email addresses if you want me to add you to the team.

**Comment by JimiC** [comment]
Have a look at the proposition branch. There I'm creating two `docker` images. One that creates our own custom `node` image and a second that creates the `vsi` image. I separated them because the `node` image takes a profound amount of time to built, something that the user may not be willing to go through every time in case he wants to build the `vsi` image multiple times.
The other reason is that the second image will only require a change the `FROM` declaration when we change the `node` version and we could have the ability to build targeting multiple `node` versions.

As for the `docker hub` access, I'll open an account asap and notify you personally.
