### ISSUE TITLE
Cannot find vsicons.settings.json when use --user-data-dir by CLI

### ISSUE THREAD

**Issue by xiazeyu** [vscode-icons/vscode-icons#1572]
- [x] I'm sure this issue is not a _duplicate_.
- More info:
> Related, but not solve my problem:
https://github.com/vscode-icons/vscode-icons/issues/1101
https://github.com/vscode-icons/vscode-icons/issues/1123

I was using `cmder`, and make vsCode portable by using this command:

```batch
@cmd /c "start %cmder_root%\bin\vsCode\Code.exe --user-data-dir %cmder_root%\bin\vsCode\data\userData --extensions-dir %cmder_root%\bin\vsCode\data\extension %* %cmder_root%\bin\vsCode\data\code.code-workspace"
```

and it seems that your plugin cannot detect my custom `user-data-dir` passed by CLI.

It throws out like this:
```
[Extension Host] Activating extension `robertohuertasm.vscode-icons` failed:  ENOENT: no such file or directory, open 'C:\Users\xiaze\AppData\Roaming\Code\User\vsicons.settings.json'
[Extension Host] Here is the error stack:  Error: ENOENT: no such file or directory, open 'C:\Users\xiaze\AppData\Roaming\Code\User\vsicons.settings.json'
	at Object.fs.openSync (fs.js:584:18)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
	at Object.fs.writeFileSync (fs.js:1326:33)
	at SettingsManager.setState (I:\bin\vsCode\data\extension\robertohuertasm.vscode-icons-7.23.0\out\src\settings\settingsManager.js:75:12)
	at SettingsManager.updateStatus (I:\bin\vsCode\data\extension\robertohuertasm.vscode-icons-7.23.0\out\src\settings\settingsManager.js:82:14)
	at initialize (I:\bin\vsCode\data\extension\robertohuertasm.vscode-icons-7.23.0\out\src\index.js:22:25)
	at activate (I:\bin\vsCode\data\extension\robertohuertasm.vscode-icons-7.23.0\out\src\index.js:39:5)
	at Function.t._callActivateOptional (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:592)
	at Function.t._callActivate (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:271)
	at i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:720:336
	at Object.g [as _notify] (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:654)
	at K.then.o.(anonymous function) (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:868)
	at Object.g [as _notify] (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:654)
	at K.then.o.(anonymous function) (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:868)
	at Object.g [as _notify] (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at e.resolveOk (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:525:85)
	at e._receiveReply (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:227)
	at e._receiveOneMessage (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:524)
	at i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:596:384
	at i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:463
	at i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
	at e.fire (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at Socket.<anonymous> (i:\bin\vsCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
激活扩展“robertohuertasm.vscode-icons”失败: ENOENT: no such file or directory, open 'C:\Users\xiaze\AppData\Roaming\Code\User\vsicons.settings.json'。
```

When I look into the source code, I found that:

https://github.com/vscode-icons/vscode-icons/blob/master/src/utils/index.ts#L23
https://github.com/vscode-icons/vscode-icons/blob/master/src/settings/settingsManager.ts#L27

It was looking into `%APPDATA%` instead of `%cmder_root%\bin\vsCode\data\userData` I passed to vsCode.exe.

Is there any way to solve this?

**Comment by JimiC** [comment]
Nope. We are currently not supporting this. Thought, we will look into providing this feature, if possible.

**Comment by JimiC** [comment]
Tech Debt: https://github.com/Microsoft/vscode/issues/2741

**Comment by JimiC** [comment]
@xiazeyu Does the new portable mode suits your needs?

**Comment by xiazeyu** [comment]
@JimiC 
It works on my case.
(Notice that it only works on the latest vsCode version)

Wait for you to publish it on the vsCode market.

**Comment by JimiC** [comment]
Unfortunately `API` request for `CLI` usage is still pending (https://github.com/Microsoft/vscode/issues/49306).
