### ISSUE TITLE
[Task] Adjust icons to make pixel perfect 

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1613]
As pointed out by @mpodciwinski, our icons aren't pixel perfect and it's about time to fix that.

A good reference about pixel perfect icon designing: https://www.youtube.com/watch?v=KYpVtDj-xQs

**Comment by mpodciwinski** [comment]
@JimiC it's sounds good for me.
I attach 2 folder samples [Dropbox](https://www.dropbox.com/sh/z3yxxjklljf9oil/AAD24kIkATR2i5CBEbI38Cc9a?dl=0)
Check with yourself, and write to me or see the differences before and after.

**Comment by JimiC** [comment]
Looking at your icons I have the following requests:
- The icon MUST have a 2px margin from all sides, meaning if the artwork is a 32x32 canvas, the background icon should always be 28x28.
- The background icon SHOULD be centered. 
- The overlaying icon MUST be no more than 21x21px and MUST always be placed on the right bottom corner with a 1px margin from right and bottom.

**Comment by mpodciwinski** [comment]
@JimiC Ok, but now can you send me folder with examples? or write me how I can easily create own?

You guidelines is not correct. I will describe them exactly tomorrow.

**Comment by JimiC** [comment]
We have no folder with examples. All icons are in the [icons folder](https://github.com/vscode-icons/vscode-icons/tree/master/icons).

**Comment by mpodciwinski** [comment]
I know, but how i want see how icon look in VsCode, must create folder (or file) with this extension. This is problematic.

**Comment by JimiC** [comment]
Yeah. you see the examples generator is a lagcy tool. I made it when we switched from `PNG` to `SVG` and at that time we didn't have implemented the `language id` support. So all the icons that are supported via a language highlighting extension will not show if the extension is not installed in `vscode`.

There is though a workaround by using the customization feature. This works if you follow [these](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning) instructions.

**Comment by mpodciwinski** [comment]
Don't be angry for me, but i can not do this. It's too hard for me now. :sweat:
I just start with code, i am beginner. Before this, i was only designing, i still do this, but it's time learning something new. Meybe thats why i saw this not perfect icons. :grin:

 I would be grateful if you do this himself and publish.

**Comment by JimiC** [comment]
I can help you further tomorrow.

**Comment by mpodciwinski** [comment]
Thank's :v:

**Comment by JimiC** [comment]
@mpodciwinski Turns out that `examples-generator` has a bug on `Windows`. Some bug was in `wpilgenerator`, I fixed that but forgot to do the same with the `examples-generator` It works on `*nix` OSes though. So I assume you are working on `Windows` (hench you working with `Ai`).

So until I get the fix in, you can start with the folders manually in `vscode`.
- Create a folder named `examples`.
- Under `examples` folder, create a folder using as name any value from the `Folder Name` column in the [folders list](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders).

The icon should show up.

Now if you want to test your icons simply replace the existing icon (make a backup first just in case) in the icons folder. Then start `Launch Extension` from the Debugger (F5) and open the `examples` folder in the new `vscode` instance that will pop-up.

**Comment by JimiC** [comment]
If you have any link I can read or watch on why our guidelines aren't correct, I would appreciate it much.

**Comment by mpodciwinski** [comment]
@JimiC ok, give me a sign if you fix it and generate examples.

**Comment by mpodciwinski** [comment]
@JimiC i did as you wrote:
> Now if you want to test your icons simply replace the existing icon (make a backup first just in case) in >the icons folder. Then start Launch Extension from the Debugger (F5) and open the examples folder in >the new vscode instance that will pop-up.

but some errors appear to me [Error screencast](https://www.dropbox.com/s/clb0bk5oppk2is5/2018-06-04_11h40_19.mp4?dl=0)

![2018-06-04_11h44_17](https://user-images.githubusercontent.com/39386011/40910529-a7730dbc-67ec-11e8-8e8c-c862dfa6580f.png)

And when I preview the file's file it still leads to the installation folder.
I'm doing something wrong?

**Comment by JimiC** [comment]
That means that the project did not build. Try `npm run build`. If all goes well you will see a success message in console. Otherwise, post back any error message.

**Comment by mpodciwinski** [comment]
output from shell:
```shell
PS D:\Dropbox\Folder zespołu Inspect\Repo\github\vscode-icons> npm run build

> vscode-icons@7.23.0 prebuild D:\Dropbox\Folder zespołu Inspect\Repo\github\vscode-icons
> npm run lint && npm run test


> vscode-icons@7.23.0 lint D:\Dropbox\Folder zespołu Inspect\Repo\github\vscode-icons
> tslint -p .

'tslint' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-icons@7.23.0 lint: `tslint -p .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-icons@7.23.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mpodc\AppData\Roaming\npm-cache\_logs\2018-06-04T10_44_33_250Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-icons@7.23.0 prebuild: `npm run lint && npm run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-icons@7.23.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mpodc\AppData\Roaming\npm-cache\_logs\2018-06-04T10_44_33_288Z-debug.log
```

I've installed all the recommended packages.

**Comment by JimiC** [comment]
Delete ` node_modules` folder and install the dependencies again via `npm i`. Something must have gone wrong in the first install.

**Comment by JimiC** [comment]
You are in trouble. The `Git` installation seems busted.

**Comment by JimiC** [comment]
Do me a favor and tell me what `npde -v` and `npm -v` returns?

**Comment by mpodciwinski** [comment]
Maybe, but other project works correct with git.
I will reinstall `Git` and see what happens.

```shell
PS C:\Users\mpodc\Desktop\vscode-icons> node -v
v8.11.2
PS C:\Users\mpodc\Desktop\vscode-icons> npm -v
6.1.0
PS C:\Users\mpodc\Desktop\vscode-icons>

```

**Comment by JimiC** [comment]
`Node` and `npm` looks good although we use `Node 7.9.0` for the project to be inline with the `node` version `vscode` uses.

Can you perform `git submodule update --init --recursive` on the project directly?

**Comment by mpodciwinski** [comment]
Reinstal `Git` and still this same.
Yes, i try. 😢

**Comment by mpodciwinski** [comment]
I do not know if this is important, but I meant it as a "change" for files and I did not change anything there.
![2018-06-04_16h01_13](https://user-images.githubusercontent.com/39386011/40921771-baa92b18-6810-11e8-9507-116a9ad0bcee.png)

**Comment by JimiC** [comment]
You need to revert any changes.

**Comment by mpodciwinski** [comment]
I do not make any changes to the entire `root`, except changing the same `svg` files. These changes in the submodule it creates itself after typing `npm i` in console.

**Comment by JimiC** [comment]
I'm at a loss here. I don't know how to help you further.

**Comment by mpodciwinski** [comment]
Thanks anyway, i give up too.
I will wait until you solve the problems you mentioned above. ✌️

**Comment by JimiC** [comment]
Stil,l you will have to resolve the issue with `npm install`. Even fixing the bug `examples-generator` is a submodule of the project.

**Comment by JimiC** [comment]
@mpodciwinski I figured out your issue. It's a bub with `npm 6.1.0` (https://github.com/npm/npm/issues/20815)

Since some commits have been made to the project it's prudent to fetch those commits before you try the following workaround.

There are two ways to bypass the error:

1. Downgrade `npm` to `5.10.0` by typing `npm i -g npm@5.10.0`.

or

2. Remove the `preinstall` script from `package.json` and perform a manual `git submodule update --init --recursive`.

Then proceed with `npm i` as usual. In case of 2, revert the removal of the `preinstall` script.

**Comment by mpodciwinski** [comment]
I did as you said, install node 7.9.0 and npm 5.10.0.

```shell
❯ node -v
v7.9.0
❯ npm -v
5.10.0
```
but still 😞 
```shell
> vscode-icons@7.23.0 preinstall /Users/michal_mac/Dropbox/Folder zespołu Inspect/Repo/github/vscode-icons
> git submodule update --init --recursive


> nodegit@0.18.3 install /Users/michal_mac/Dropbox/Folder zespołu Inspect/Repo/github/vscode-icons/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs:
   [ '-c',
     '/Users/michal_mac/Dropbox/Folder\\ zespołu\\ Inspect/Repo/github/vscode-icons/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/michal_mac/Dropbox/Folder\\ zespołu\\ Inspect/Repo/github/vscode-icons/node_modules/nodegit/vendor/openssl/openssl' ],
  cmd: '/Users/michal_mac/Dropbox/Folder\\ zespołu\\ Inspect/Repo/github/vscode-icons/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/michal_mac/Dropbox/Folder\\ zespołu\\ Inspect/Repo/github/vscode-icons/node_modules/nodegit/vendor/openssl/openssl' }

[nodegit] ERROR - Could not finish preinstall
{ Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs:
   [ '-c',
     '/Users/michal_mac/Dropbox/Folder\\ zespołu\\ Inspect/Repo/github/vscode-icons/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/michal_mac/Dropbox/Folder\\ zespołu\\ Inspect/Repo/github/vscode-icons/node_modules/nodegit/vendor/openssl/openssl' ],
  cmd: '/Users/michal_mac/Dropbox/Folder\\ zespołu\\ Inspect/Repo/github/vscode-icons/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/michal_mac/Dropbox/Folder\\ zespołu\\ Inspect/Repo/github/vscode-icons/node_modules/nodegit/vendor/openssl/openssl' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.18.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.18.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michal_mac/.npm/_logs/2018-06-09T15_52_34_852Z-debug.log
```
Even how i delete preinstall script. Still this same error.
I don't know why he installs this script as I removed it.
```
"preinstall": "git submodule update --init --recursive",
```

**Comment by JimiC** [comment]
> Since some commits have been made to the project it's prudent to fetch those commits before you try the following workaround.

**Comment by mpodciwinski** [comment]
I missed it.
Now it's works! 😄 
Thanks!

**Comment by JimiC** [comment]
@mpodciwinski Have you abandoned the task?

**Comment by mpodciwinski** [comment]
No, I'm still working. there is a lot to do.

**Comment by JimiC** [comment]
Good to know.

**Comment by JimiC** [comment]
@mpodciwinski FYI, you can update `npm` to 6.4+ as the bug with the `submodule` was fixed.

**Comment by KingDarBoja** [comment]
Does this task still in progress? Because there is a option to make every icon pixel perfect for their current size (32x32) without having to rely on those steps. Just right click on the selection and select "Generate Pixel Perfect" and adobe Illustrator will automatically modify the svg sizes to make it fit the grid as stated by the guidelines. 

Example with the default file icon:
![image](https://user-images.githubusercontent.com/30560560/53062268-43435f80-348e-11e9-8d09-2d5a6f103159.png)

**Comment by JimiC** [comment]
Illustrator version?

**Comment by KingDarBoja** [comment]
@JimiC Adobe Illustrator CC 2019 :)
