### ISSUE TITLE
Support for Workspace Settings is broken

### ISSUE THREAD

**Issue by Serega124** [vscode-icons/vscode-icons#1686]
- [x] I'm sure this issue is not a _duplicate_.

Extension will fail to load if both User Settings and Workspace Settings contains entry `vsicons.associations.files` (or `vsicons.associations.folders`)

<details>
<summary>Devtools console log</summary>

```
Activating extension `robertohuertasm.vscode-icons` failed:  TypeError: Cannot assign to read only property 'files' of object
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:209
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 [Extension Host] Here is the error stack:  Error: TypeError: Cannot assign to read only property 'files' of object
	at Object.set (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:565:575)
	at Object.getVsiconsConfig (D:\Soft\VSCode\data\extensions\robertohuertasm.vscode-icons-7.25.0\out\src\utils\vscode-extensions.js:15:41)
	at Object.<anonymous> (D:\Soft\VSCode\data\extensions\robertohuertasm.vscode-icons-7.25.0\out\src\commands\index.js:18:47)
	at Object.<anonymous> (D:\Soft\VSCode\data\extensions\robertohuertasm.vscode-icons-7.25.0\out\src\commands\index.js:271:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:831:951)
	at Function.o._load (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:781:881)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (D:\Soft\VSCode\data\extensions\robertohuertasm.vscode-icons-7.25.0\out\src\init\welcome.js:9:20)
	at Object.<anonymous> (D:\Soft\VSCode\data\extensions\robertohuertasm.vscode-icons-7.25.0\out\src\init\welcome.js:73:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:831:951)
	at Function.o._load (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:781:881)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (D:\Soft\VSCode\data\extensions\robertohuertasm.vscode-icons-7.25.0\out\src\init\index.js:6:10)
	at Object.<anonymous> (D:\Soft\VSCode\data\extensions\robertohuertasm.vscode-icons-7.25.0\out\src\init\index.js:10:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:831:951)
	at Function.o._load (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:781:881)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous> (D:\Soft\VSCode\data\extensions\robertohuertasm.vscode-icons-7.25.0\out\src\index.js:5:14)
	at Object.<anonymous> (D:\Soft\VSCode\data\extensions\robertohuertasm.vscode-icons-7.25.0\out\src\index.js:51:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:831:951)
	at Function.o._load (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:781:881)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Function.i [as __$__nodeRequire] (d:\Soft\VSCode\resources\app\out\vs\loader.js:30:770)
	at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:807:367
	at t._doActivateExtension (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:807:479)
	at t._activateExtension (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:806:337)
	at Object.actualActivateExtension (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:804:204)
	at e._activateExtension (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:459:497)
	at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:459:116
	at Array.map (<anonymous>)
	at e._activateExtensions (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:459:91)
	at e.activateByEvent (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:457:367)
	at t.activateByEvent (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:804:568)
	at t.handleEagerExtensions (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:828:359)
	at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:827:570
	at Object.g [as _notify] (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:971)
	at Object.enter (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:277)
	at n.Class.derive._oncancel._run (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:100)
	at n.Class.derive._oncancel._completed (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:559)
	at e.open (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:113:375)
	at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:804:242
	at Object.g [as _notify] (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:971)
	at Object.enter (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:277)
	at n.Class.derive._oncancel._run (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:100)
	at n.Class.derive._oncancel._completed (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:559)
	at c (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:1011)
	at $.then.o.(anonymous function) (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:86:205)
	at Object.g [as _notify] (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:971)
	at Object.enter (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:277)
	at n.Class.derive._oncancel._run (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:83:100)
	at n.Class.derive._oncancel._completed (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:559)
	at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:117:1020
	at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:150:661
	at LOOP (original-fs.js:1757:14)
	at _combinedTickCallback (internal/process/next_tick.js:131:7)
	at process._tickCallback (internal/process/next_tick.js:180:9)
```

</details>
<br>
Extension version: 7.25.0<br>
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)<br>
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: enabled_force_on<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_force_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled_force<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (12.06GB free)|
|Process Argv|D:\Soft\VSCode\Code.exe|
|Screen Reader|no|
|VM|67%|

</details>

**Comment by JimiC** [comment]
We are aware and preparing a fix with our next major update
