### ISSUE TITLE
Uninstall script fails

### ISSUE THREAD

**Issue by ntwb** [vscode-icons/vscode-icons#2378]
Here's the output after uninstalling this extension:
```
[2020-02-18 13:13:38.280] [sharedprocess] [info] vscode-icons-team.vscode-icons 10.0.0 Running post uninstall script
[2020-02-18 13:13:38.396] [sharedprocess] [error] vscode-icons-team.vscode-icons 10.0.0 post-uninstall internal/modules/cjs/loader.js:630
    throw err;
    ^

Error: Cannot find module '/Users/netweb/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/out/src/uninstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:850:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

[2020-02-18 13:13:38.406] [sharedprocess] [error] vscode-icons-team.vscode-icons 10.0.0 Failed to run post uninstall script: post-uninstall process exited with code 1
[2020-02-18 13:13:38.511] [sharedprocess] [info] Deleted from disk vscode-icons-team.vscode-icons /Users/netweb/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0
```

Installed the extension again and the path and file do not exist:

- `/Users/netweb/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/out/src/uninstall.js`

Only `dist`, `icons`, and `images` folders in the `/Users/netweb/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/` path and the various package.json files in the root

**Comment by JimiC** [comment]
Thanks for bringing this to our attention.
